[[redirects]]
  from = "/api"
  to = "https://cold-bush-2928.fly.dev/api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"